// Demo catalog data — fully fictional, neutral placeholder content.
// Swap these entries for your own legal items (projects, tools, resources).
window.CATALOG_ITEMS = [
  {
    id: "a1",
    name: "Aurora Notes",
    category: "Productivity",
    author: "Studio Northlight",
    version: "1.4.2",
    updated: "2026-08-14",
    tags: ["markdown", "offline", "sync"],
    price: "Free",
    rating: 4.7,
    downloads: 12840,
    short: "A calm, distraction-free note app with local-first storage.",
    description:
      "Aurora Notes keeps your writing fast and private. Everything is stored locally by default, with optional end-to-end encrypted sync. Includes markdown preview, tagging, and a focus mode.",
  },
  {
    id: "b2",
    name: "PixelForge",
    category: "Graphics",
    author: "Rowan Vega",
    version: "3.0.0",
    updated: "2026-09-02",
    tags: ["pixel-art", "editor", "animation"],
    price: "Free",
    rating: 4.9,
    downloads: 28110,
    short: "An open pixel-art editor with onion-skinning and tilemaps.",
    description:
      "PixelForge is a lightweight editor for pixel art and sprite animation. It supports layers, palettes, onion-skinning, and tilemap export. Built for hobbyists and indie game artists.",
  },
  {
    id: "c3",
    name: "LoopStation",
    category: "Audio",
    author: "Cadence Labs",
    version: "2.1.5",
    updated: "2026-07-28",
    tags: ["daw", "loops", "midi"],
    price: "Free",
    rating: 4.5,
    downloads: 9432,
    short: "A minimal loop-based music sketchpad in your browser.",
    description:
      "LoopStation lets you layer beats, melodies, and samples into quick musical sketches. MIDI input, per-track effects, and export to WAV. Great for prototyping song ideas.",
  },
  {
    id: "d4",
    name: "TerraMap",
    category: "Tools",
    author: "Open Carto Collective",
    version: "0.9.1",
    updated: "2026-06-19",
    tags: ["maps", "geojson", "viewer"],
    price: "Free",
    rating: 4.3,
    downloads: 5120,
    short: "Render and inspect GeoJSON layers with a clean viewer.",
    description:
      "TerraMap is a small viewer for geospatial data. Drop in GeoJSON files, toggle layers, and inspect feature properties. No account needed, runs entirely client-side.",
  },
  {
    id: "e5",
    name: "SnapKit",
    category: "Graphics",
    author: "Mira Osei",
    version: "1.2.0",
    updated: "2026-09-10",
    tags: ["screenshots", "mockups", "export"],
    price: "Free",
    rating: 4.6,
    downloads: 17600,
    short: "Turn plain screenshots into polished, framed mockups.",
    description:
      "SnapKit adds backgrounds, device frames, and shadows to your screenshots in seconds. Batch export at multiple resolutions for docs, stores, and social posts.",
  },
  {
    id: "f6",
    name: "QueryLens",
    category: "Developer",
    author: "Basalt Tools",
    version: "4.5.3",
    updated: "2026-08-30",
    tags: ["sql", "database", "explorer"],
    price: "Free",
    rating: 4.8,
    downloads: 21050,
    short: "A friendly SQL explorer with schema diagrams.",
    description:
      "QueryLens connects to local databases and gives you a fast query editor, auto-generated schema diagrams, and safe read-only mode for exploring unfamiliar data.",
  },
  {
    id: "g7",
    name: "FocusTimer",
    category: "Productivity",
    author: "Studio Northlight",
    version: "2.0.0",
    updated: "2026-05-11",
    tags: ["pomodoro", "focus", "minimal"],
    price: "Free",
    rating: 4.4,
    downloads: 8300,
    short: "A tiny, tidy Pomodoro timer that stays out of your way.",
    description:
      "FocusTimer runs quiet work/break cycles with gentle notifications and a daily summary. No sign-up, no tracking, just a clean timer that helps you keep momentum.",
  },
  {
    id: "h8",
    name: "MeshViewer",
    category: "Graphics",
    author: "Rowan Vega",
    version: "1.7.4",
    updated: "2026-09-18",
    tags: ["3d", "obj", "gltf"],
    price: "Free",
    rating: 4.7,
    downloads: 14220,
    short: "Preview 3D models (OBJ / glTF) right in the browser.",
    description:
      "MeshViewer loads OBJ and glTF models with orbit controls, wireframe toggle, and basic material inspection. Perfect for quickly checking exported assets.",
  },
  {
    id: "i9",
    name: "ClipVault",
    category: "Tools",
    author: "Cadence Labs",
    version: "3.3.0",
    updated: "2026-07-04",
    tags: ["clipboard", "history", "snippets"],
    price: "Free",
    rating: 4.2,
    downloads: 6740,
    short: "A searchable clipboard history and snippet manager.",
    description:
      "ClipVault remembers what you copy and lets you pin frequently used snippets. Fuzzy search, tags, and local encryption keep everything organized and private.",
  },
  {
    id: "j10",
    name: "MarkFlow",
    category: "Developer",
    author: "Basalt Tools",
    version: "5.1.0",
    updated: "2026-09-20",
    tags: ["docs", "markdown", "static-site"],
    price: "Free",
    rating: 4.9,
    downloads: 30410,
    short: "Write docs in markdown, publish a static site instantly.",
    description:
      "MarkFlow turns a folder of markdown files into a searchable static documentation site. Themes, code highlighting, and a live preview server are all included.",
  },
];
