# -*- coding: utf-8 -*-
"""Eén plek waar de indeling van de items staat, gedeeld door de
overzichtsplaat en de keuringspagina."""
import sprites_armor
import sprites_items2 as I2

DYES = [d for d, _c in I2.DYES]


def groups():
    return [
        ("Voedsel & oogst",
         "Wat je eet en oogst — hier telt of de kleur eetbaar oogt.",
         ["apple", "golden_apple", "enchanted_golden_apple", "bread", "carrot",
          "golden_carrot", "baked_potato", "poisonous_potato", "beetroot",
          "wheat", "wheat_seeds", "honeycomb", "cookie", "pumpkin_pie",
          "melon_slice", "glistering_melon_slice", "sweet_berries",
          "glow_berries", "dried_kelp", "chorus_fruit", "popped_chorus_fruit",
          "bowl", "mushroom_stew", "beetroot_soup", "rabbit_stew",
          "suspicious_stew", "rotten_flesh", "spider_eye", "fermented_spider_eye"]),
        ("Vlees & vis",
         "Rauw is roder en zachter, gebakken bruiner en droger — dat verschil moet je in de hotbar zien.",
         ["beef", "cooked_beef", "porkchop", "cooked_porkchop", "chicken",
          "cooked_chicken", "mutton", "cooked_mutton", "rabbit", "cooked_rabbit",
          "cod", "cooked_cod", "salmon", "cooked_salmon", "tropical_fish",
          "pufferfish"]),
        ("Harnas",
         "Vier silhouetten, zeven materialen. De leren overlay staat in grijstinten omdat het spel die met jouw verfkleur inkleurt.",
         list(sprites_armor.items())),
        ("Grondstoffen",
         "Losse buit uit de wereld.",
         ["stick", "coal", "charcoal", "flint", "clay_ball", "leather",
          "rabbit_hide", "string", "feather", "bone", "slime_ball",
          "ender_pearl", "magma_cream", "blaze_rod", "brick", "nether_brick",
          "snowball", "egg", "ink_sac", "glow_ink_sac", "cocoa_beans",
          "phantom_membrane", "rabbit_foot", "turtle_scute", "armadillo_scute",
          "nautilus_shell", "ghast_tear", "nether_star", "ender_eye",
          "heart_of_the_sea"]),
        ("Staven & klompjes",
         "Zelfde vorm, per materiaal een ander natuurpalet.",
         ["iron_ingot", "gold_ingot", "copper_ingot", "netherite_ingot",
          "raw_iron", "raw_copper", "raw_gold", "netherite_scrap",
          "iron_nugget", "gold_nugget"]),
        ("Kristallen & stof",
         "De felle kleuren — deze moeten opvallen zonder te schreeuwen.",
         ["diamond", "emerald", "amethyst_shard", "lapis_lazuli", "quartz",
          "prismarine_shard", "prismarine_crystals", "echo_shard", "redstone",
          "glowstone_dust", "gunpowder", "sugar", "blaze_powder", "bone_meal"]),
        ("Drank & flesjes",
         "De vloeistof in potion_overlay staat in grijstinten: het spel kleurt die met het effect mee.",
         ["glass_bottle", "potion", "potion_overlay", "splash_potion",
          "lingering_potion", "experience_bottle", "ominous_bottle",
          "honey_bottle"]),
        ("Boeken & papier",
         "Zelfde bandvorm, andere kaft.",
         ["book", "writable_book", "written_book", "enchanted_book",
          "knowledge_book", "paper", "map", "filled_map", "name_tag"]),
        ("Uitrusting",
         "De boog heeft drie spanframes, anders springt hij terug naar vanilla.",
         ["bow", "bow_pulling_0", "bow_pulling_1", "bow_pulling_2", "arrow",
          "shears", "flint_and_steel", "fishing_rod", "fishing_rod_cast",
          "spyglass", "brush", "lead", "saddle", "totem_of_undying"]),
        ("Emmers",
         "Bast met een rank als hengsel; alleen de inhoud verschilt.",
         ["bucket", "water_bucket", "lava_bucket", "milk_bucket",
          "powder_snow_bucket", "cod_bucket", "salmon_bucket",
          "pufferfish_bucket", "tropical_fish_bucket", "axolotl_bucket",
          "tadpole_bucket"]),
        ("Kleurstoffen",
         "Plantaardig geverfd: zachter en grijzer dan vanilla.",
         [f"{d}_dye" for d in DYES]),
        ("Zaden",
         "Klein en licht, zodat ze niet met de kleurstoffen te verwarren zijn.",
         ["melon_seeds", "pumpkin_seeds", "beetroot_seeds", "torchflower_seeds",
          "pitcher_pod"]),
    ]
